ip: 192.168.12.12:9876
topic: print_send_msg
rtopic: print_send_msg_r
tag: ai_fuwuqi_1 #tag必须唯一
name: AI服务器里的
accesskey: 
secretkey: 
myip: 192.168.12.36
myport: 23123
consulip: 192.168.12.12
consulport: 8500